version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: amie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - mynetwork
  amie:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_KEY: ${JWT_KEY}
      APP_ENV: "development"
      PAGE_TAKE: ${PAGE_TAKE}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: redis
      SENDGRID_PORT: ${SENDGRID_PORT}
      SENDGRID_HOST: ${SENDGRID_HOST}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_USERNAME: ${SENDGRID_USERNAME}
      SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL}
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
